server:
  port: 5000

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    function:
      definition: publishCaseImport
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: case.import

  data:
    elasticsearch:
      enabled : false
      host: localhost
      port: 9200
      index: case-server
      type: metadatas
