name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -Pjacoco package sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-case-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        if: github.ref == 'refs/heads/master'
        run: >
          mvn --batch-mode jib:build
          -Djib.httpTimeout=60000
          -Djib.to.image=docker.io/powsybl/case-server
          -Djib.to.auth.username=powsyblci
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}
